# 网关路由配置
gateway:
  route:
    # 开发环境静态资源端点
    dev-endpoint: http://127.0.0.1:8099
    # 主服务端点
    host-endpoint: http://127.0.0.1:8089
  sys:
    # 最大请求体大小限制
    max-request-size: 1MB
    # 上传文件时最大请求体大小限制
    max-file-size: 36MB

    # 验证码配置
    captcha:
      # 验证码页面路径
      page-path: /static/captcha.html
      # 触发验证码机制的IP数量阈值
      trigger-ip-threshold: 50
      # 解除验证码机制的IP数量阈值
      release-ip-threshold: 10
      # IP统计窗口时间（秒）
      ip-statistics-window-seconds: 10
      # 白名单有效期（分钟）
      whitelist-validity-minutes: 5
      # 是否启用严格验证码模式（启用后所有请求都需要验证码验证）
      strict-mode: false
      # 是否允许API请求在验证码激活时继续访问
      allow-api-when-captcha-active: true

    # 安全配置
    security:
      # 是否启用HTTP安全头
      enable-security-headers: true
      # 是否启用Cookie安全设置
      enable-secure-cookies: true
      # 内容安全策略
      content-security-policy: "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; frame-src 'self';"
      # Referrer策略
      referrer-policy: no-referrer
      # X-Frame-Options值
      frame-options: SAMEORIGIN


logging:
  level:
    com.dev.gateway.logging: DEBUG

